from src.core.graph import Graph
from src.visual.graph_visual import GraphVisualizer

graph1 = Graph(directed=True)
graph1.add_edge('A', 'B', 2)
graph1.add_edge('A', 'C', 3)
graph1.add_edge('B', 'D', 5)
graph1.add_edge('B', 'E', 3)
graph1.add_edge('D', 'F', 1)
graph1.add_edge('D', 'G', 7)
graph1.add_edge('F', 'M', 6)
graph1.add_edge('G', 'H', 4)
graph1.add_edge('G', 'I', 3)
graph1.add_edge('H', 'M', 2)
graph1.add_edge('H', 'N', 5)
graph1.add_edge('I', 'N', 1)
graph1.add_edge('E', 'J', 4)
graph1.add_edge('J', 'I', 2)
graph1.add_edge('J', 'L', 2)
graph1.add_edge('L', 'O', 3)
graph1.add_edge('L', 'U', 5)
graph1.add_edge('C', 'E', 6)
graph1.add_edge('C', 'P', 2)
graph1.add_edge('P', 'S', 3)
graph1.add_edge('P', 'R', 9)
graph1.add_edge('S', 'T', 6)
graph1.add_edge('T', 'U', 3)
graph1.add_edge('T', 'V', 7)
graph1.add_edge('A', 'W', 6)
graph1.add_edge('W', 'Q', 6)
graph1.add_edge('W', 'X', 3)
graph1.add_edge('W', 'Y', 5)
graph1.add_edge('Q', 'R', 2)
graph1.add_edge('X', 'Z', 2)
graph1.add_edge('Y', 'Z', 3)
graph1.add_edge('Z', 'V', 5)

graph_plot = GraphVisualizer(graph1)

graph_plot.draw(title="Test graph image")